Eriks branch
PBaranovskyi/learningJava pull request #1
Opened 2017-04-07 09:18 UTC by R2D200

home work 2 - Pavliuk Erik

2017-04-09 15:42 UTC, PBaranovskyi commented on homeworks/src/erik/module2/Work143.java
> +            System.out.println((number1 && number2) != number2); // not understood operator !
Есть вопрос по оператору?

2017-04-09 15:48 UTC, R2D200 commented
Когда я ставлю ! Идея не выполнЕт код, не могу его исподьзовать (или
использую не прввильно)

9 апр. 2017 г. 18:42 пользователь "PBaranovskyi" <notifications@github.com>
написал:

> *@PBaranovskyi* commented on this pull request.
> ------------------------------
>
> In homeworks/src/erik/module2/Work143.java
> <https://github.com/PBaranovskyi/learningJava/pull/1#discussion_r110545210>
> :
>
> > @@ -0,0 +1,16 @@
> +package erik.module2;
> +
> +/**
> + * Created by Erik Pavliuk on 07/04/2017.
> + */
> +public class Work143 {
> +    public static void main(String[] args) {
> +            boolean number1 = true;
> +            boolean number2 = false;
> +            System.out.println(number1 && number2);
> +            System.out.println(number1 || number2);
> +            System.out.println(number1 ^ number2);
> +            System.out.println((number1 && number2) != number2); // not understood operator !
>
> Есть вопрос по оператору?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/PBaranovskyi/learningJava/pull/1#pullrequestreview-31727164>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AXdp2jj0K6Gt3egGraSNKXHrpZdIMWOjks5ruPyBgaJpZM4M2p3F>
> .
>

2017-04-09 16:04 UTC, PBaranovskyi commented on homeworks/src/erik/module2/Work141.java
> +        float number5 = 234.23523523F; // почему не могу записать число с плавающей точкой?
Что значит не можешь? Ты записал его. Но для Float ты обязан указать F после литерала - иначе оно трактуется компилятором по умолчанию как double - и его уже надо приводить к float вручную; Например float number5=  (float) 234.324;

2017-04-09 16:05 UTC, PBaranovskyi requested changes
Где задачи с Hacker rank? Я о них в письме писал

2017-04-09 16:07 UTC, R2D200 commented
С флоатом все понятно. Не понятно почему когда пишеш а ! b  то идея выдает
ошибку. Завтра покажу

9 апр. 2017 г. 19:04 пользователь "PBaranovskyi" <notifications@github.com>
написал:

> *@PBaranovskyi* commented on this pull request.
> ------------------------------
>
> In homeworks/src/erik/module2/Work141.java
> <https://github.com/PBaranovskyi/learningJava/pull/1#discussion_r110545623>
> :
>
> > @@ -0,0 +1,25 @@
> +package erik.module2;
> +
> +/**
> + * Created by Erik Pavliuk on 07/04/2017.
> + */
> +public class Work141 {
> +    public static void main(String[] args) {
> +        byte number1 = 12;
> +        short number2 = 10001;
> +        int number3 = 685*112;
> +        long number4 = 8723;
> +        float number5 = 234.23523523F; // почему не могу записать число с плавающей точкой?
>
> Что значит не можешь? Ты записал его. Но для Float ты обязан указать F
> после литерала - иначе оно трактуется компилятором по умолчанию как double
> - и его уже надо приводить к float вручную; Например float number5= (float)
> 234.324;
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/PBaranovskyi/learningJava/pull/1#pullrequestreview-31727597>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AXdp2t5qbLLb1EAj-jZpZTvoDi-lTgtAks5ruQF5gaJpZM4M2p3F>
> .
>

2017-04-09 16:21 UTC, PBaranovskyi commented on homeworks/src/erik/module2/Work143.java
> +            System.out.println((number1 && number2) != number2); // not understood operator !
Что по твоему должен делать оператор !  в выражении a!b ? Где а и b я так понимаю числа. Есть 4 битвайс оператора
a = 0011 1100 
b = 0000 1101 
----------------- 
a&b = 0000 1100 
a|b = 0011 1101 
a^b = 0011 0001 
~a = 1100 0011

2017-04-09 16:43 UTC, R2D200 commented
Просто я думал что NOT пишется ! А не так ~ . Теперь все стало на свои
места.  Спасибо!)

9 апр. 2017 г. 19:21 пользователь "PBaranovskyi" <notifications@github.com>
написал:

> *@PBaranovskyi* commented on this pull request.
> ------------------------------
>
> In homeworks/src/erik/module2/Work143.java
> <https://github.com/PBaranovskyi/learningJava/pull/1#discussion_r110545910>
> :
>
> > @@ -0,0 +1,16 @@
> +package erik.module2;
> +
> +/**
> + * Created by Erik Pavliuk on 07/04/2017.
> + */
> +public class Work143 {
> +    public static void main(String[] args) {
> +            boolean number1 = true;
> +            boolean number2 = false;
> +            System.out.println(number1 && number2);
> +            System.out.println(number1 || number2);
> +            System.out.println(number1 ^ number2);
> +            System.out.println((number1 && number2) != number2); // not understood operator !
>
> Что по твоему должен делать оператор ! в выражении a!b ? Где а и b я так
> понимаю числа. Есть 4 битвайс оператора
> a = 0011 1100
> b = 0000 1101
>
> a&b = 0000 1100
> a|b = 0011 1101
> a^b = 0011 0001
> ~a = 1100 0011
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/PBaranovskyi/learningJava/pull/1#discussion_r110545910>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AXdp2lspRUDUCSOZh4YAPujv-EUXGsOhks5ruQWHgaJpZM4M2p3F>
> .
>

2017-04-14 12:42 UTC, PBaranovskyi requested changes
Жду задачи с  хакер ранка

2017-04-14 12:43 UTC, PBaranovskyi commented
Жду задачи с  хакер ранка

2017-04-14 12:43 UTC, closed without merging