Krasilnikov homew work2
PBaranovskyi/learningJava pull request #12
Opened 2017-04-11 09:59 UTC by krasilnikovas

Home work 2 and hakerrand home work 1 + 2

2017-04-18 12:31 UTC, PBaranovskyi requested changes

2017-04-18 12:31 UTC, PBaranovskyi commented on homeworks/src/oleksanderkrasilnikov/HW1.java
> +        System.out.println("/: " + a/b);
Попробуй при делении получить дробное число а не 0.

2017-04-18 12:31 UTC, PBaranovskyi commented on homeworks/src/oleksanderkrasilnikov/homework2/LabWork153.java
> +                System.out.print(" " + j*i+ "| ");
Отформатируй код

2017-04-18 12:57 UTC, krasilnikovas commented
Fixed issues

2017-04-18 14:44 UTC, PBaranovskyi requested changes

2017-04-18 14:44 UTC, PBaranovskyi commented on homeworks/src/oleksanderkrasilnikov/HW1.java
> +        double a = 2;
a and b make integer , but result of a / b should be double

2017-04-19 11:10 UTC, krasilnikovas commented
Fixed requested changes

2017-04-19 12:34 UTC, merged