Kpobozhny labwork_1_5 completed
PBaranovskyi/learningJava pull request #17
Opened 2017-04-11 22:44 UTC by kpobozhny

2017-04-13 15:39 UTC, PBaranovskyi approved these changes
All is good. Will merge next week in order to give other a chance to  do it by them own.

2017-04-18 12:57 UTC, PBaranovskyi requested changes

2017-04-18 12:57 UTC, PBaranovskyi commented on homeworks/src/kpobozhny/homework/labwork_1_5/labwork_1_5_4.java
> +        for (int i = 1; i < 300; i++) {
Use ctrl+alt+L for formatting. PLease format your previous code

2017-04-18 12:57 UTC, PBaranovskyi commented on homeworks/src/kpobozhny/homework/labwork_1_5/labwork_1_5_2.java
> +                    default: if(x>9){System.out.println("Other"); }
what if x < 0?

2017-04-18 12:57 UTC, PBaranovskyi commented on homeworks/src/kpobozhny/homework/labwork_1_5/labwork_1_5_2.java
> +                    case 2: System.out.println("Two");break;
format your code. CTRL+ALT+L

2017-04-18 12:57 UTC, PBaranovskyi commented on homeworks/src/kpobozhny/homework/labwork_1_5/labwork_1_5_2.java
> +                    case 5: System.out.println("Five");break;
Maybe it`s better to use one string variable assigned to a value in each case and print it with one System.out.println  after case in the end?.

2017-04-18 12:57 UTC, PBaranovskyi commented on homeworks/src/kpobozhny/homework/labwork_1_5/labwork_1_5_5.java
> +                System.out.println("The Sum is:"+sum);
format the code

2017-04-18 12:57 UTC, PBaranovskyi commented on homeworks/src/kpobozhny/homework/labwork_1_5/labwork_1_5_7.java
> +
format the code

2017-04-18 18:44 UTC, kpobozhny commented on homeworks/src/kpobozhny/homework/labwork_1_5/labwork_1_5_2.java
> +                    default: if(x>9){System.out.println("Other"); }
I have mentioned this case in my comments .
//it was not described in the task what should be done if we have a negative number (x<1), so let's do nothing.

2017-04-18 18:51 UTC, kpobozhny commented on homeworks/src/kpobozhny/homework/labwork_1_5/labwork_1_5_2.java
> +                    case 5: System.out.println("Five");break;
yes, completely agree. fixed.

2017-04-18 18:54 UTC, kpobozhny commented
Requested changes implemented.

2017-04-19 12:23 UTC, merged