HomeWork1 by ederkachenko
PBaranovskyi/learningJava pull request #18
Opened 2017-04-12 07:37 UTC by esderkachenko

2017-04-18 12:26 UTC, PBaranovskyi requested changes

2017-04-18 12:26 UTC, PBaranovskyi commented on homeworks/src/evgeniyderkachenko/module1/LabWork143.java
> +        System.out.println(c= a&&b);
Use ctrl+alt+L for formatting. PLease format your code

2017-04-18 12:26 UTC, PBaranovskyi commented on homeworks/src/evgeniyderkachenko/module1/LabWork143.java
> +        boolean c,d,e,f;
Why are you declaring c,d,e,f; if you do not use it?

2017-04-18 12:26 UTC, PBaranovskyi commented on homeworks/src/evgeniyderkachenko/module1/LabWork148.java
> +        System.out.println("l="+((int)s)); //тут можно потерять данные
каким образом делая из short  - интеджер можно потерять данные?

2017-04-19 07:51 UTC, esderkachenko commented on homeworks/src/evgeniyderkachenko/module1/LabWork143.java
> +        boolean c,d,e,f;
Fixed

2017-04-19 07:52 UTC, esderkachenko commented on homeworks/src/evgeniyderkachenko/module1/LabWork143.java
> +        System.out.println(c= a&&b);
Fixed

2017-04-19 07:54 UTC, esderkachenko commented on homeworks/src/evgeniyderkachenko/module1/LabWork148.java
> +        System.out.println("l="+((int)s)); //тут можно потерять данные
Не туда коммент оставил в коде. 
Исправлено

2017-04-19 12:33 UTC, PBaranovskyi commented on homeworks/src/evgeniyderkachenko/module1/LabWork143.java
> +        System.out.println(c= a&&b);
Where?

2017-05-05 09:21 UTC, closed without merging