add hackerrank tasks, day 10
PBaranovskyi/learningJava pull request #34
Opened 2017-04-19 13:01 UTC by Korsh

2017-04-21 12:09 UTC, PBaranovskyi commented on homeworks/src/andriiarzhanov/com/hackerrank/Day4_Class_vs_Instance/Day4_Class_vs_Instance.java
> +        int T = sc.nextInt();
Did you check it on hackerrank?

2017-04-22 14:36 UTC, Korsh commented on homeworks/src/andriiarzhanov/com/hackerrank/Day4_Class_vs_Instance/Day4_Class_vs_Instance.java
> +        int T = sc.nextInt();
This part is default code from task. I copied all code from task just for correct work of project
![image](https://cloud.githubusercontent.com/assets/2251075/25305337/2493dd96-2782-11e7-987b-97bff03ec1a1.png)

2017-05-05 10:52 UTC, PBaranovskyi requested changes

2017-05-05 10:52 UTC, PBaranovskyi commented on homeworks/src/andriiarzhanov/com/hackerrank/Day6_Lets_Review/Day6_Lets_Review.java
> +            String stringVar = "", even = "", odd = "";
Make each in new line

2017-05-05 10:52 UTC, PBaranovskyi commented on homeworks/src/andriiarzhanov/com/hackerrank/Day7_Arrays/Day7_Arrays.java
> +            stringVar = stringVar + arr[k] + " ";
You don`t actually need this stringVar variable - you can print straight in for loop

2017-05-14 08:49 UTC, Korsh commented on homeworks/src/andriiarzhanov/com/hackerrank/Day7_Arrays/Day7_Arrays.java
> +            stringVar = stringVar + arr[k] + " ";
done

2017-05-14 08:49 UTC, Korsh commented on homeworks/src/andriiarzhanov/com/hackerrank/Day6_Lets_Review/Day6_Lets_Review.java
> +            String stringVar = "", even = "", odd = "";
done

2017-05-19 09:43 UTC, merged