kpobozhny. homework04( currency converter + triangle). hackerrank Days08-09
PBaranovskyi/learningJava pull request #43
Opened 2017-04-23 12:34 UTC by kpobozhny

2017-04-26 14:01 UTC, PBaranovskyi requested changes

2017-04-26 14:01 UTC, PBaranovskyi commented on homeworks/src/kpobozhny/homework/hw_04/currencyconverter/CurrencyConverter.java
> +        CurrencyConverter currencyConverter = new CurrencyConverter(0.037);
Why rate not 26.68 uah for 1 USD?

2017-04-26 14:01 UTC, PBaranovskyi commented on homeworks/src/kpobozhny/homework/hw_04/triangle/Triangle.java
> +                ((A.getY() == point.getY()) && (B.getY() == point.getY()))) {
Code duplication - you can avoid it if you will store your vertexes in array for example. (Not A,B,C but 1,2,3 and method signature would be not setVertexC(point) but setVertex(index, point))

2017-04-26 14:01 UTC, closed without merging

2017-04-29 15:00 UTC, kpobozhny commented on homeworks/src/kpobozhny/homework/hw_04/currencyconverter/CurrencyConverter.java
> +        CurrencyConverter currencyConverter = new CurrencyConverter(0.037);
fixed.

2017-04-29 15:01 UTC, kpobozhny commented on homeworks/src/kpobozhny/homework/hw_04/triangle/Triangle.java
> +                ((A.getY() == point.getY()) && (B.getY() == point.getY()))) {
added new class Triangle2.