home task 1
PBaranovskyi/learningJava pull request #6
Opened 2017-04-09 10:53 UTC by Tretykhlib

Please take a look at  home task 1

2017-04-10 19:37 UTC, PBaranovskyi reviewed
good - добавь задачу с типами из хакерранка

2017-04-12 12:53 UTC, Tretykhlib commented
added task from hackerrank

2017-04-14 12:46 UTC, PBaranovskyi commented
Format all your code please with ctrl+alt +L . And add tasks from hacker rank please

2017-04-18 08:54 UTC, Tretykhlib commented
Please merge with master

2017-04-18 12:29 UTC, PBaranovskyi requested changes

2017-04-18 12:29 UTC, PBaranovskyi commented on homeworks/src/ltretykhlib/module1/example/Hackerrank2.java
> +        str= scan.nextLine();
why two times nextLine?

2017-04-18 12:29 UTC, PBaranovskyi commented on homeworks/src/ltretykhlib/module1/example/PrimitiveDataTypes.java
> +        float f = 100.1f;
use please Upper case literal suffixes

2017-04-18 12:29 UTC, PBaranovskyi commented on homeworks/src/ltretykhlib/module1/example/ArithmeticOperators.java
> +        int div=a/b;
Format all your code please with ctrl+alt +L

2017-04-18 14:46 UTC, Tretykhlib commented on homeworks/src/ltretykhlib/module1/example/PrimitiveDataTypes.java
> +        float f = 100.1f;
change applied

2017-04-18 14:46 UTC, Tretykhlib commented on homeworks/src/ltretykhlib/module1/example/ArithmeticOperators.java
> +        int div=a/b;
change applied

2017-05-05 09:20 UTC, merged